# Generated by Django 3.2.2 on 2021-05-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phno', models.CharField(max_length=100)),
                ('customer_addr', models.CharField(max_length=100)),
                ('insert_dt', models.DateTimeField()),
                ('update_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('item_id', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=100)),
                ('order_dt', models.DateTimeField()),
                ('update_dt', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField()),
                ('payment_dt', models.DateTimeField()),
                ('updated_dt', models.DateTimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orders', to_field='order_id')),
            ],
        ),
    ]
