# Generated by Django 3.2.2 on 2021-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_addr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(max_length=100),
        ),
    ]
