# Generated by Django 3.2.2 on 2021-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210506_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
