# Generated by Django 3.2.2 on 2021-05-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orders_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_addr',
            field=models.TextField(max_length=255),
        ),
    ]
