# Generated by Django 3.2.2 on 2021-05-06 17:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_customer_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phno',
            field=models.CharField(max_length=10, validators=[core.models.validate_length]),
        ),
    ]
